version: '3.8'

services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    networks:
      - mean-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    image: mohsin101177/mean-crud-backend:latest
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/meancrud?retryWrites=true
    networks:
      - mean-network
    command: sh -c "sleep 120 && node server.js"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    image: mohsin101177/mean-crud-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - mean-network
    depends_on:
      - backend

networks:
  mean-network:
    driver: bridge

volumes:
  mongo-data: